CC = gcc
target: byn single

byn: byn.c beggar.c riffle.c
	$(CC) -o byn byn.c beggar.c riffle.c riffle.h beggar.h

single: single.c beggar.c riffle.c
	$(CC) -o single single.c beggar.c riffle.c riffle.h beggar.h
